#! /bin/sh

pgrep -x sxhkd > /dev/null		|| sxhkd -c $XDG_CONFIG_HOME/sxhkd/bspwm_sxhkdrc  $XDG_CONFIG_HOME/sxhkd/sxhkdrc &
#pgrep -x sxhkd > /dev/null		|| sxhkd  &
pgrep -x picom > /dev/null		|| picom --config ~/.config/picom/config --experimental-backend &
pgrep -x flameshot > /dev/null	|| flameshot &

#killall redshift
#redshift -l 48.716385:21.261074 &

killall lemonbar succade pactl
succade &
xdo lower -m -N Bar &

~/.fehbg &
setxkbmap -layout us,ru -option grp:win_space_toggle -option caps:capslock
xinput set-prop "ETD2303:00 04F3:3083 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ETD2303:00 04F3:3083 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ETD2303:00 04F3:3083 Touchpad" "libinput Disable While Typing Enabled" 0

bspc monitor -d     V      ﭮ 
bspc config ignore_ewmh_focus true

bspc config border_width        2
bspc config window_gap          8

bspc config single_monocle		true
bspc config gapless_monocle		true
bspc config borderless_monocle	true

bspc rule -r *

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a floaterm state=floating sticky=on locked=true

bspc rule -a discord desktop=^9
bspc rule -a TelegramDesktop desktop=^10
bspc rule -a Slack desktop=^4


bspc config border_width 1
bspc config focused_border_color \#40e0d0

